---
- name: Start backend server
  shell: |
    cd ~/application/source/backend/
    npm install
    npm run build
    pm2 start dist/main.js
  register: output
  
- debug:
    var: output.stdout_lines