version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test-backend:
    executor:
      name: node/default
    steps:
      - checkout
      - run: cd backend && npm i && npm run test
  test-frontend:
    executor:
      name: node/default
    steps:
      - checkout
      - run: cd frontend && npm i && npm run test
  build-backend:
    executor:
      name: node/default
    steps:
      - checkout
      - run: cd backend && npm i && npm run build
  build-frontend:
    executor:
      name: node/default
    steps:
      - checkout
      - run: cd frontend && npm i && npm run build
workflows:
    build-and-test:
      jobs:
        - test-frontend
        - test-backend
          requires: test-frontend
        - build-frontend
            requires: test-backend
        - build-backend
          requires: build-frontend