version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test-backend:
    working_directory: ~/Automated-pipeline
    executor:
      name: node/default
    steps:
      - checkout
      - run: cd backend
      - run: npm i
      - run: npm run test
  build-and-test-frontend:
    working_directory: ~/Automated-pipeline
    executor:
      name: node/default
    steps:
      - checkout
      - run: cd frontend
      - run: npm i
      - run: npm run test
workflows:
    build-and-test:
      jobs:
        - build-and-test-frontend
        - build-and-test-backend